### ISSUE TITLE
FormItReCaptcha giving errors in log / modx Revolution 2.6.3-pl / php 7.0.29 / formIt 4.0.1-pl

### ISSUE THREAD

**Issue by gravinos** [sepiariver/recaptchav2#27]
After upgrading to FormIt 4.0.1-pl, every time I load the form I get the error

[2018-05-02 09:33:07] (ERROR @ .../core/components/formit/src/FormIt/Request.php : 87) [FormIt] Unable to load FormItReCaptcha.

modx Revolution 2.6.3-pl
PHP Version 7.0.29
formIt 4.0.1-pl
ReCaptchaV2 2.3.0-rc1

RecaptchaV2 appears, but returns error and not send the form.

FormIt issue discussion: #https://github.com/Sterc/FormIt/issues/170

**Comment by RiodeJaneiroo** [comment]
i have the same problem(

**Comment by tvset** [comment]
i have the same problem(

**Comment by eremozin** [comment]
i have the same issue

**Comment by terrybarth** [comment]
Similar issue. Different behaviors.

My contact form IS sending the emails successfully.  Yet, the error log is filling up with:  

...public_html/core/components/formit/src/FormIt/Request.php : 87) [FormIt] Could not load FormItReCaptcha service class.

I'm using the Invisible Captcha. I know that this working because after repeated tests, it promoted me to choose images from a grid.

I don't know if this is related, but the the redirect hook is not working, nor is the FormItAutoResponder hook. However the FormItSaveForm is working.

&hooks=`recaptchav2,email,FormItSaveForm,FormItAutoResponder,redirect,` 

Modx 2.6.3
PHP Version 7.0.30
formIt 4.0.1-pl
ReCaptchaV2 2.3.0-rc1

I happen to have another site with virtually the same setup that is working perfectly. The only difference from what I've described above is Modx 2.6.0

Update: I've resolved the other issues with hooks not working. It was not related to ReCaptchaV2. I still have the errors in the log though.

**Comment by alexgillon** [comment]
Having the same issue as terrybarth, everything works fine, I just keep getting the below error in the MODX log:

[2018-06-19 21:21:46] (ERROR @ /home/*********/public_html/core/components/formit/src/FormIt/Request.php : 87) [FormIt] Could not load FormItReCaptcha service class.

**Comment by travisbotello** [comment]
Same issue here...

**Comment by xceed-will** [comment]
same issue here

**Comment by watou** [comment]
same issue here

**Comment by Kvodnon** [comment]
same issue here 2.6.5

**Comment by waizen** [comment]
Same here on multiple sites after upgrading many sites to 2.6.5. However, the form does get submitted and email sent out. Page reloads with "Please select the checkbox in the ReCaptcha image." error message. Does not redirect to thank you page, causing site visitor to believe nothing has happend. Visitor usually submits multiple times, each time gettign reCaptcha error.

Error log filling up with same OP stated error message.

MODx 2.6.5
PHP7.0
Formit 4.1.0-pl
ReCaptchaV2 2.3.0-rc1

**Comment by DESIGNfromWITHIN** [comment]
Same here...

**Comment by sebastian-marinescu** [comment]
It's working, but still filling up with this not-understandable error :)

**Comment by davidcmoody** [comment]
This fixed the issue for me.  No more error log filling up.

https://github.com/Sterc/FormIt/issues/170#issuecomment-387549784

**Comment by sepiariver** [comment]
Closing as it looks to be a FormIt issue https://github.com/Sterc/FormIt/issues/170 that was introduced in 4.0.1
