### ISSUE TITLE
Timeout with ReCaptcha on pageload

### ISSUE THREAD

**Issue by marcbyte64** [sepiariver/recaptchav2#52]
By generating the token on pageload, the form has to be filled out within 2 minutes:
https://developers.google.com/recaptcha/docs/verify

We set an autorefresh of the token within the tpl, maybe something you want to implement.

**Comment by sepiariver** [comment]
Did you observe that happening using V3? I’ve read the invisible Re captcha is supposed to detect user interactions and “just work”? Also the documentation on refreshing seems to all be with respect to V2 which implies V3 doesn’t need it, but I guess the .execute() function can be called again on a timer—was that what you did?

(I think I would add the approach to the docs or a blog post rather than try to change the implementation for every install. What do you think?)

**Comment by marcbyte64** [comment]
Happens with V3, not sure if the same problem occurs with V2 as well. And yes, we implemented a refresh of the token via timer but creating the token on submit would be the proper solution I guess. 

I'd implement it within the package so it is solved for good but having it mentioned somewhere, would at least help those people facing this problem in the future. Entirely up to you :)

**Comment by rabesocke** [comment]
I have the same problem with V3 on a client site.

Google itself recommend to get the token when submitting the form (https://developers.google.com/recaptcha/docs/v3).

At the moment I solve this issue with a refresh timer (like darQrrR).

**Comment by sepiariver** [comment]
Ok this seems like a good candidate for a guide or some documentation with code examples. Hopefully will have a chance over the holidays to write that up

**Comment by sepiariver** [comment]
Hopefully this will help: https://sepiariver.com/modx/a-guide-to-recaptcha-v3-for-modx-cms/

**Comment by steffan-culd** [comment]
I managed to solve it like this:
`<script src="https://www.google.com/recaptcha/api.js?render=[[+site_key]]&hl=[[++cultureKey]]&onload=initRecaptcha" defer></script>
<input type="hidden" name="[[+token_key]]">
<input type="hidden" name="[[+action_key]]" value="[[+form_id]]">
<script>
    
    function initRecaptcha(){
        grecaptcha.ready(function() {
      
            var form = $("form");
            $("#submitbutton").on("click",function(){
               grecaptcha.execute('[[+site_key]]', {action: '[[+form_id]]'}).then(function(token) {
                    document.querySelector('[name="[[+token_key]]"]').value = token;
                    form.submit();
                    
                });
            });

        });
    }
</script>`
Instead of using a submit button, I add a 'regular' button (without type="submit") and check when it's clicked. Before submitting the form I execute the grecaptcha and then submit the form.

Any remarks or ideas?

**Comment by sepiariver** [comment]
Yep this works. Since the user is invoking it when they click to submit the form, there should be very little chance that they will time out. The call to recaptcha is blocking but that seems to be fast, generally.
