### ISSUE TITLE
Блокировка отображения

### ISSUE THREAD

**Issue by retyui** [sepiariver/recaptchav2#7]
### Чтобы не блокировать загрузку cтраницы!!!

```
jsToBottom
    Insert JS code (or a link) at the end of the page, before < / body >.
Uses modX.regClientScript.
    [[+jsTV:jsToBottom]] 

```

**Comment by retyui** [comment]
examples

```
[[+blablablaTv:default=`https://www.google.com/recaptcha/api.js?hl=[[++cultureKey]]`:jsToBottom]] 
```

**Comment by sepiariver** [comment]
You don't have to use the default Chunk, it's only there for convenience. You can modify the Chunk from:

```
<div class="g-recaptcha" data-sitekey="[[+site_key]]"></div>
<script type="text/javascript" src="https://www.google.com/recaptcha/api.js?hl=[[++cultureKey]]"></script>
```

to:

```
<div class="g-recaptcha" data-sitekey="[[+site_key]]"></div>
```

and then call your script tag wherever you want. I don't think I want to register JS with the snippet because it gives even less control to the end user—what if for some reason somebody doesn't want to register the script at all, because they've included it elsewhere, or maybe they want it at the top in the header? 

If you call your own Chunk, and call your own script tag somewhere, you have maximum control ;)
